os: osx
sudo: true
install:
  - chmod +x ./Scripts/Install.sh
  - chmod +x ./Scripts/Build.sh
  - ./Scripts/Install.sh
script:
  - ./Scripts/Build.sh
on_failure:
  - cat Unity.log
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: Build
  on:
    branch: master
