os: osx
sudo: true
install:
  - chmod +x ./Scripts/Install.sh
  - ./Scripts/Install.sh
  - travis_wait 30
script:
  - /Applications/Unity/Unity.app/Contents/MacOS/Unity -nographics -silent-crashes -logFile /dev/stdout -projectpath ./ -quit -batchmode -executeMethod Util.Build
  - ls Build
