os: osx
language: objective-c
osx_image: xcode61
sudo: true
rvm:
  - 2.1.2
install:
  - chmod +x ./Scripts/Install.sh
  - ./Scripts/Install.sh
  - travis_wait 30
script:
  - /Applications/Unity/Unity.app/Contents/MacOS/Unity -nographics -silent-crashes -logFile /dev/stdout -projectpath ./ -quit -batchmode -executeMethod Util.Build
  - ls Build
