install:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - gem install u3d
  - u3d dependencies
  - u3d install latest_stable --packages Unity,Linux,Mac,WebGL,Windows
script:
  - echo WIP
