os: osx
sudo: true
install:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export U3D_PASSWORD=
  - ./Scripts/Install.sh
  - travis_wait 30
script:
  - /Applications/Unity/Unity.app/Contents/MacOS/Unity -nographics -silent-crashes -logFile /dev/stdout -projectpath /Users/travis/build/TheBrokenRail/RogueRobots -executeMethod Util.Build -quit -batchmode
  - ls Build
